services:
  aquadata:
    tty: true
    build: .
    links:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    image: mysql
    environment:
      LANG: pt_BR.UTF-8
      LANGUAGE: pt_BR:pt
      LC_ALL: pt_BR.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aquadata
      MYSQL_USER: aquadata
      MYSQL_PASSWORD: aquadata
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
